book_title_id = "id-productTitle"
kindle_cost_id = "id-mediaTab_heading_0"
paperback_cost_id = "id-mediaTab_heading_1"
product_details_xpath = "xpath-//*[@id='productDetailsTable']/tbody/tr/td/div/ul"
details = "tag-li"